package yadi.samuraiai.foundation.certification;

public enum FoundationRequirement {
    FOUNDATION_AUDIT, CLIENT_SERVER_SEPARATION, CUSTOMNPC_COMPATIBILITY, VOICE_CORE,
    RUNTIME, EVENT_BUS, AI_QUEUE, SCHEDULER, THREAD_AUDIT, COMPATIBILITY_SUITE,
    REGRESSION_SUITE, PERFORMANCE_SUITE
}
