package yadi.samuraiai.client.voice.core;

public enum VoiceEngineState { UNINITIALIZED, BOOTSTRAPPING, INSTALLING, DOWNLOADING_MODEL, VERIFYING_MODEL, LOADING_ENGINE, READY, BUSY, UPDATING, ERROR, DISABLED }
